
#/***************************************************************************
# * Copyright 2005 Philippe Kernevez All rights reserved.                   *
# * Please look at license.txt for more license detail.                     *
# **************************************************************************/

UPDATE METHOD_CALL SET PARENT_INDEX_IN_FLOW=NULL;

UPDATE EXECUTION_FLOW SET FIRST_METHOD_CALL_INDEX_IN_FLOW=NULL;

DELETE FROM method_call;

DELETE FROM execution_flow;


-- MySQL dump 10.9
--
-- Host: localhost    Database: monitoring
-- ------------------------------------------------------
-- Server version	4.1.10a-nt

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;

/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;

/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;

/*!40101 SET NAMES utf8 */;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


LOCK TABLES execution_flow WRITE;

INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25010,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25011,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25012,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25013,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25014,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25015,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25016,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25017,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25018,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25019,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25020,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);
INSERT INTO execution_flow (ID, THREAD_NAME, DURATION, BEGIN_TIME_AS_DATE, END_TIME, JVM, BEGIN_TIME) VALUES (25021,'ExecuteThread: ''23'' for queue: ''weblogic.kernel.Default''',151,'2005-04-22 15:03:58',1114175038609,'Kerny''s Babasse',1114175038458);

UNLOCK TABLES;


LOCK TABLES method_call WRITE;

/* 25010 */
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,1,NULL,'org.javamonitoring.snapshot.application.interop.soa.ejb.AbstractEAIReportEJBSessionBean','getStatOfHoldings',1114175038458,1114175038609,'[[Input: getStatOfHoldingsRequest:[GetStatOfHoldingsRequest: entity: INVPAR poonType: 001 statementType: 002 valorisationIndicator: 1 nullPoonIndicator: 0 estimatedAmountCurre','[Result: getStatOfHoldingsResponse: [GetGS',NULL,NULL,NULL,'EJB');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,2,0,'org.javamonitoring.snapshot.framework.interop.ejb.EJBSession','createApplicationRequestContext',1114175038459,1114175038459,'[]','[mUserLogin = user_ok mUserId = null mUserPassword',NULL,NULL,1,'EJB');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,3,1,'org.javamonitoring.snapshot.framework.interop.ejb.EJBSession','getEJBContext',1114175038459,1114175038459,'[]','weblogic.ejb20.internal.SessionEJBContextImpl@10bc',NULL,NULL,1,'EJB');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,4,2,'org.javamonitoring.snapshot.framework.interop.ejb.EJBSession','getOrchestrationService',1114175038459,1114175038465,'[weblogic.ejb20.internal.SessionEJBContextImpl@10bc1d5[mUserLogin = user_ok mUserId = null mUserPassword = password mApplicationDate = null mEntityId = 0 mEntityLabel = null mUserId = null mLanguage =','org.javamonitoring.snapshot.application.interop.orchestration.statemen',NULL,NULL,1,'EJB');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,5,0,'org.javamonitoring.snapshot.framework.interop.orchestrationservice.OrchestrationService','setEJBContext',1114175038464,1114175038464,'[weblogic.ejb20.internal.SessionEJBContextImpl@10bc1d5]','void',NULL,NULL,4,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,6,1,'org.javamonitoring.snapshot.framework.interop.orchestrationservice.OrchestrationService','setContext',1114175038465,1114175038465,'[[mUserLogin = user_ok mUserId = null mUserPassword = password mApplicationDate = null mEntityId = 0 mEntityLabel = null mUserId = null mLanguage = en mLanguageCountry = GB mConnectionToken = 0 mEntit','void',NULL,NULL,4,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,7,3,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getStatOfHoldings',1114175038465,1114175038609,'[[Input: getStatOfHoldingsRequest: [GetStatOfHoldingsRequest: entity: INVPAR poonType: 001 statementType: 002 valorisationIndicator: 1 nullPoonIndicator: 0 estimatedAmountCurre','[Result: getStatOfHoldingsResponse: [GetGS',NULL,NULL,1,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,8,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','validateInput',1114175038481,1114175038481,'[[GetStatOfHoldingsRequest: entity: INVPAR poonType: 001 statementType: 002 valorisationIndicator: 1 nullPoonIndicator: 0 estimatedAmountCurrency: EUR dates: [Dates: dateIndicator: 001','void',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,9,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','convertError',1114175038481,1114175038481,'[null]','void',NULL,NULL,8,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,10,1,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getStatOfHoldingsOrchestrationServiceHel',1114175038481,1114175038483,'[]','org.javamonitoring.snapshot.application.interop.orchestration.statemen',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,11,0,'org.javamonitoring.snapshot.framework.interop.orchestrationservice.OrchestrationService','setContext',1114175038483,1114175038483,'[[mUserLogin = user_ok mUserId = null mUserPassword = password mApplicationDate = null mEntityId = 0 mEntityLabel = null mUserId = null mLanguage = en mLanguageCountry = GB mConnectionToken = 0 mEntit','void',NULL,NULL,10,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,12,1,'org.javamonitoring.snapshot.framework.interop.orchestrationservice.OrchestrationService','setContext',1114175038483,1114175038483,'[[mUserLogin = user_ok mUserId = null mUserPassword = password mApplicationDate = null mEntityId = 0 mEntityLabel = null mUserId = null mLanguage = en mLanguageCountry = GB mConnectionToken = 0 mEntit','void',NULL,NULL,10,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,13,2,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','createStatOfHoldingsQueryInput',1114175038483,1114175038483,'[[GetStatOfHoldingsRequest: entity: INVPAR poonType: 001 statementType: 002 valorisationIndicator: 1 nullPoonIndicator: 0 estimatedAmountCurrency: EUR dates: [Dates: dateIndicator: 001','[ISINCode=null | accountForecasts=null | accounts=',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,14,3,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getCurrentAccountingDate',1114175038488,1114175038532,'[INVPAR]','[DateSCT: Date: Fri Jul 09 00:00:00 CEST 2004]',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,15,0,'org.javamonitoring.snapshot.framework.interop.orchestrationservice.OrchestrationService','getBasicService',1114175038488,1114175038493,'[[mUserLogin = user_ok mUserId = null mUserPassword = password mApplicationDate = null mEntityId = 0 mEntityLabel = null mUserId = null mLanguage = en mLanguageCountry = GB mConnectionToken = 0 mEntit','org.javamonitoring.snapshot.application.server.basicservice.accounting',NULL,NULL,14,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,16,1,'org.javamonitoring.snapshot.application.server.datamgr.accountingdate.AccountingDateDataMgr','selectByFonctionalKey',1114175038500,1114175038530,'[INVPAR]','[accountingDate=[DateSCT: Date: Fri Jul 09 00:00:0',NULL,NULL,14,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,17,0,'org.javamonitoring.snapshot.common.server.datamgr.SelectableDataMgr','getKey',1114175038500,1114175038501,'[.select_by_functionalKey_by_ticker]','CURRENT_ACCOUNTING_DATE.select_by_functionalK',NULL,NULL,16,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,18,0,'org.javamonitoring.snapshot.application.server.datamgr.accountingdate.AccountingDateDataMgr','getKeyRoot',1114175038501,1114175038501,'[]','CURRENT_ACCOUNTING_DATE',NULL,NULL,17,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,19,1,'org.javamonitoring.snapshot.common.server.datamgr.SelectableDataMgr','selectInternalByFonctionalKey',1114175038501,1114175038524,'[_CURRENT_ACCOUNTING_DATE.select_by_functionalKey_by_ticker[INVPAR]]','[accountingDate=[DateSCT: Date: Fri Jul 09 00:00:0',NULL,NULL,16,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,20,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','getJDBCWrapper',1114175038501,1114175038515,'[]','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW',NULL,NULL,19,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,21,0,'org.javamonitoring.snapshot.application.server.datamgr.AbstractDataMgr','getPoolConfigFileName',1114175038501,1114175038501,'[]','org.javamonitoring.snapshot.application.server.techserver',NULL,NULL,20,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,22,1,'org.javamonitoring.snapshot.framework.server.datamgr.DataMgr','getJDBCWrapper',1114175038501,1114175038515,'[org.javamonitoring.snapshot.application.server.techserver]','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW',NULL,NULL,20,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,23,0,'java.sql.Connection','prepareStatement',1114175038513,1114175038513,'[{call DBMS_APPLICATION_INFO.SET_CLIENT_INFO(?)}]','weblogic.jdbc.wrapper.PreparedStatement_weblogic_j',NULL,NULL,22,'SqlPrepare');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,24,1,'java.sql.PreparedStatement','setString',1114175038513,1114175038513,'[1user_ok]','void',NULL,NULL,22,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,25,2,'java.sql.PreparedStatement','executeUpdate',1114175038514,1114175038515,'[]','1',NULL,NULL,22,'SqlExecute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,26,1,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','executeSelect',1114175038516,1114175038521,'[_CURRENT_ACCOUNTING_DATE.select_by_functionalKey_by_ticker[INVPAR]org.javamonitoring.snapshot.framework.server.datamgr.JdbcWrapper@99b6af]','org.javamonitoring.snapshot.fra mework.server.datamgr.JdbcW',NULL,NULL,19,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,27,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','beginMethod',1114175038516,1114175038517,'[_CURRENT_ACCOUNTING_DATE.select_by_functionalKey_by_ticker]','1114175038516',NULL,NULL,26,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,28,1,'org.javamonitoring.snapshot.application.server.datamgr.AbstractDataMgr','getSqlSelectFileName',1114175038517,1114175038517,'[]','org.javamonitoring.snapshot.application.server.datamgr.accountingdate.',NULL,NULL,26,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,29,2,'java.sql.Connection','prepareCall',1114175038518,1114175038518,'[Select CAD_ID, CAD_ENT_ID, CAD_CURRENT_ACCOUNTING_DATE, CAD_STATUS_ENUM, CAD_LASTCLOSE_DATE, CAD_VERSION_NUMBER from _CURRENT_ACCOUNTING_DATE, V_PARR WHERE CAD_ENT_ID=PAR_ID AND PAR_TICKER=? ]','weblogic.jdbc.wrapper.CallableStatement_weblogic_j',NULL,NULL,26,'SqlPrepare');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,30,3,'java.sql.PreparedStatement','setString',1114175038518,1114175038518,'[1INVPAR]','void',NULL,NULL,26,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,31,4,'java.sql.PreparedStatement','executeQuery',1114175038519,1114175038520,'[]','weblogic.jdbc.wrapper.ResultSet_weblogic_jdbcx_bas',NULL,NULL,26,'SqlExecute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,32,5,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','endMethod',1114175038520,1114175038521,'[_CURRENT_ACCOUNTING_DATE.select_by_functionalKey_by_ticker]','void',NULL,NULL,26,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,33,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','endMethod',1114175038520,1114175038521,'[_CURRENT_ACCOUNTING_DATE.select_by_functionalKey_by_ticker1114175038516]','void',NULL,NULL,32,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,34,2,'org.javamonitoring.snapshot.application.server.datamgr.accountingdate.AccountingDateDataMgr','populateBusiness',1114175038521,1114175038522,'[org.javamonitoring.snapshot.framework.server.datamgr.JdbcWrapper@99b6af]','[accountingDate=[DateSCT: Date: Fri Jul 09 00:00:0',NULL,NULL,19,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,35,3,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','closeJdbcWrapper',1114175038524,1114175038524,'[org.javamonitoring.snapshot.framework.server.datamgr.JdbcWrapper@99b6af]','void',NULL,NULL,19,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,36,4,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getStatOfHoldingsQueryMgr',1114175038535,1114175038535,'[]','org.javamonitoring.snapshot.application.server.datamgr.securities.stat',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,37,5,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getStatOfHoldingsOrchestrationServiceHel',1114175038535,1114175038535,'[]','org.javamonitoring.snapshot.application.interop.orchestration.statemen',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,38,6,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','createDateQueryInput',1114175038536,1114175038536,'[[GetStatOfHoldingsRequest: entity: INVPAR poonType: 001 statementType: 002 valorisationIndicator: 1 nullPoonIndicator: 0 estimatedAmountCurrency: EUR dates: [Dates: dateIndicator: 001','[accountingDate=[DateSCT: Date: Thu Apr 21 00:00:0',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,39,7,'org.javamonitoring.snapshot.application.server.datamgr.securities.statofholdings.StatOfHoldingsQueryMgr','fillStatOfHoldingsResultSet',1114175038538,1114175038554,'[org.javamonitoring.snapshot.application.interop.soa.dto.gsastatofholdings.StatOfHoldingsResp onseResultSetImpl@390b1d[ISINCode=null | accountForecasts=null | accounts=[99910000001] | allCustomerAccoun','void',NULL,NULL,7,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,40,0,'org.javamonitoring.snapshot.application.server.datamgr.securities.statofholdings.StatOfHoldingsQueryMgr','execute',1114175038542,1114175038554,'[org.javamonitoring.snapshot.application.server.technical.querybuilder.builder.StatOfHoldingsQueryBuilder@108bddborg.javamo nitoring.snapshot.application.interop.soa.dto.gsastatofholdings.StatOfHoldingsResponseResult','void',NULL,NULL,39,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,41,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','getJDBCWrapper',1114175038543,1114175038543,'[]','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW',NULL,NULL,40,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,42,0,'org.javamonitoring.snapshot.application.server.datamgr.securities.statofholdings.StatOfHoldingsQueryMgr','getPoolConfigFileName',1114175038543,1114175038543,'[]','org.javamonitoring.snapshot.application.server.techserver',NULL,NULL,41,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,43,1,'org.javamonitoring.snapshot.framework.server.datamgr.DataMgr','getJDBCWrapper',1114175038543,1114175038543,'[org.javamonitoring.snapshot.application.server.techserver]','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW',NULL,NULL,41,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,44,1,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','executeSelect',1114175038543,1114175038553,'[ALL_SEC_TYP_NO_FOR_BAL_TYP_LTD_CLI_SKA_SEC_DETAIL_FORM_DETAIL_CUSTODIAN_DETAIL_CUSTODIAN_SKA_ALL_BLQ_DETAIL_AVT_DETAIL_ACCOUNTING_DATE_NO_NULL_POONS[fra, INVPAR, 350, [99910000001], Thu Apr 21 00','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW',NULL,NULL,40,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,45,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','beginMethod',1114175038544,1114175038544,'[ALL_SEC_TYP_NO_FOR_BAL_TYP_LTD_CLI_SKA_SEC_DETAIL_FORM_DETAIL_CUSTODIAN_DETAIL_CUSTODIAN_SKA_ALL_BLQ_DETAIL_AVT_DETAIL_ACCOUNTING_DATE_NO_NULL_POONS]','1114175038544',NULL,NULL,44,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,46,1,'org.javamonitoring.snapshot.application.server.datamgr.securities.statofholdings.StatOfHoldingsQueryMgr','getSqlSelectFileName',1114175038544,1114175038544,'[]','org.javamonitoring.snapshot.application.server.datamgr.securities.stat',NULL,NULL,44,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,47,2,'java.sql.Connection','prepareCall',1114175038548,1114175038548,'[select TABLE_SKAR_CUSTOMER.SKA_EXTERNAL_NUMBER CUSTOMER_SKA, VM_BDR__SECURITIES.ISIN_CODE, SEC_NAME, SET_PSEUDO, CBSN_CUSTOMER_SEC_BALANCE_SPEC.CBS_LEGAL_TYPE, TABLE_PARR_CUSTODIAN.PAR_TICKER CUS','weblogic.jdbc.wrapper.CallableStatement_weblogic_j',NULL,NULL,44,'SqlPrepare');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,48,3,'java.sql.PreparedStatement','setString',1114175038548,1114175038548,'[1fra]','void',NULL,NULL,44,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,49,4,'java.sql.PreparedStatement','setString',1114175038548,1114175038548,'[2INVPAR]','void',NULL,NULL,44,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,50,5,'java.sql.PreparedStatement','setLong',1114175038549,1114175038549,'[3350]','void',NULL,NULL,44,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,51,6,'java.sql.PreparedStatement','setString',1114175038549,1114175038549,'[499910000001]','void',NULL,NULL,44,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,52,7,'java.sql.PreparedStatement','setTimestamp',1114175038549,1114175038549,'[52005-04-21 00:00:00.0]','void',NULL,NULL,44,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,53,8,'java.sql.PreparedStatement','executeQuery',1114175038550,1114175038552,'[]','weblogic.jdbc.wrapper.ResultSet_weblogic_jdbcx_bas',NULL,NULL,44,'SqlExecute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,54,9,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','endMethod',1114175038552,1114175038553,'[ALL_SEC_TYP_NO_FOR_BAL_TYP_LTD_CLI_SKA_SEC_DETAIL_FORM_DETAIL_CUSTODIAN_DETAIL_CUSTODIAN_SKA_ALL_BLQ_DETAIL_AVT_DETAIL_ACCOUNTING_DATE_NO_NULL_POONS]','void',NULL,NULL,44, 'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,55,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','endMethod',1114175038552,1114175038553,'[ALL_SEC_TYP_NO_FOR_BAL_TYP_LTD_CLI_SKA_SEC_DETAIL_FORM_DETAIL_CUSTODIAN_DETAIL_CUSTODIAN_SKA_ALL_BLQ_DETAIL_AVT_DETAIL_ACCOUNTING_DATE_NO_NULL_POONS1114175038544]','void',NULL, NULL,54,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,56,2,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','closeJdbcWrapper',1114175038553,1114175038554,'[org.javamonitoring.snapshot.framework.server.datamgr.JdbcWrapper@e8a6a2]','void',NULL,NULL,40,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,57,8,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getStatOfHoldingsOrchestrationServiceHel',1114175038554,1114175038554,'[]','org.javamonitoring.snapshot.application.interop.orchestration.statemen',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,58,9,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','buildStatOfHoldingsTree',1114175038554,1114175038557,'[org.javamonitoring.snapshot.application.interop.soa.dto.gsastatofholdings.StatOfHol dingsResultSetResult@13d832falsefalsetruetruefalsetruetruefalsefalse]','[GetStatOfHoldingsResponse: {  } ]',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,59,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','setStatOfHoldingsResultSetResult',1114175038554,1114175038554,'[org.javamonitoring.snapshot.application.interop.soa.dto.gsastatofholdings.State mentOfHoldingsResultSetResult@13d832]','void',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,60,1,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','aggregateAvailability',1114175038555,1114175038555,'[truefalse]','void',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,61,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListBalanceQualifierAdded',1114175038555,1114175038555,'[]','[]',NULL,NULL,60,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,62,2,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','aggregateBalanceQualifier',1114175038555,1114175038555,'[truefalse]','void',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,63,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustodianSafeKeepingAccountAdded',1114175038555,1114175038555,'[]','[]',NULL,NULL,62,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,64,3,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','aggregateCustodianAccount',1114175038555,1114175038555,'[falsefalse]','void',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,65,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustodianAdded',1114175038555,1114175038555,'[]','[]',NULL,NULL,64,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,66,4,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','aggregateCustodian',1114175038555,1114175038556,'[truefalse]','void',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,67,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListSecurityLegalTypeAdded',1114175038556,1114175038556,'[]','[]',NULL,NULL,66,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,68,5,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListSecurityLegalTypeAdded',1114175038556,1114175038556,'[]','[]',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,69,6,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','selectOnlyUsedCustodians',1114175038556,1114175038556,'[[]false]','[]',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,70,7,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','aggregateSecurityLegalType',1114175038556,1114175038556,'[truefalse]','void',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,71,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListSecurityAdded',1114175038556,1114175038556,'[]','[]',NULL,NULL,70,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,72,8,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','aggregateSecurity',1114175038556,1114175038557,'[falsefalse]','void',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,73,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustomerSafeKeepingAccountAdded',1114175038556,1114175038556,'[]','[]',NULL,NULL,72,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,74,9,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','aggregateCustomerAccount',1114175038557,1114175038557,'[falsefalse]','[GetStatOfHoldingsResponse: {  } ]',NULL,NULL,58,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,75,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustomerSafeKeepingAccountAdded',1114175038557,1114175038557,'[]','[]',NULL,NULL,74,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,76,10,'org.javamonitoring.snapshot.framework.interop.orchestrationservice.OrchestrationService','getBasicService',1114175038557,1114175038560,'[[mUserLogin = user_ok mUserId = null mUserPassword = password mApplicationDate = null mEntityId = 0 mEntityLabel = null mUserId = null mLanguage = en mLanguageCountry = GB mConnectionToken = 0 mEntit','org.javamonitoring.snapshot.application2.server.basicservice.currency.C',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,77,11,'org.javamonitoring.snapshot.application2.server.datamgr.currency.CurrencyDataMgr','getByFunctionalKey',1114175038567,1114175038575,'[org.javamonitoring.snapshot.application2.server.business.functionalkey.CurrencyFunctionalKey@10da2]','[ISOCode=EUR | context=[mUserLogin = user_ok mUser',NULL,NULL,7,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,78,0,'org.javamonitoring.snapshot.common.server.datamgr.SelectableDataMgr','getKey',1114175038568,1114175038568,'[.select_by_functionnal_key]','V_CURR.select_by_functionnal_key',NULL,NULL,77,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,79,0,'org.javamonitoring.snapshot.application2.server.datamgr.currency.CurrencyDataMgr','getKeyRoot',1114175038568,1114175038568,'[]','V_CURR',NULL,NULL,78,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,80,1,'org.javamonitoring.snapshot.common.server.datamgr.SelectableDataMgr','selectInternalByFonctionalKey',1114175038568,1114175038574,'[V_CURR.select_by_functionnal_key[EUR]]','[ISOCode=EUR | context=[mUserLogin = user_ok mUser',NULL,NULL,77,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,81,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','getJDBCWrapper',1114175038568,1114175038568,'[]','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW',NULL,NULL,80,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,82,0,'org.javamonitoring.snapshot.application2.server.datamgr.AbstractSSLDataMgr','getPoolConfigFileName',1114175038568,1114175038568,'[]','org.javamonitoring.snapshot.application2.server.techserver',NULL,NULL,81,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,83,1,'org.javamonitoring.snapshot.framework.server.datamgr.DataMgr','getJDBCWrapper',1114175038568,1114175038568,'[org.javamonitoring.snapshot.application2.server.techserver]','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW',NULL,NULL,81,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,84,1,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','executeSelect',1114175038569,1114175038572,'[V_CURR.select_by_functionnal_key[EUR]org.javamonitoring.snapshot.framework.server.datamgr.JdbcWrapper@ad9f8a]','org.javamonitoring.snapshot.framework.server.datamgr.JdbcW', NULL,NULL,80,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,85,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','beginMethod',1114175038569,1114175038569,'[V_CURR.select_by_functionnal_key]','1114175038569',NULL,NULL,84,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,86,1,'org.javamonitoring.snapshot.application2.server.datamgr.AbstractSSLDataMgr','getSqlSelectFileName',1114175038569,1114175038569,'[]','org.javamonitoring.snapshot.application2.server.datamgr.currency.Curren',NULL,NULL,84,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,87,2,'java.sql.Connection','prepareCall',1114175038570,1114175038570,'[Select CUR_ID , CUR_ISO_CODE, CUR_DECIMAL_NUMBER from V_CURR WHERE CUR_ISO_CODE=?]','weblogic.jdbc.wrapper.CallableStatement_weblogic_j',NULL,NULL,84,'SqlPrepare');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,88,3,'java.sql.PreparedStatement','setString',1114175038570,1114175038570,'[1EUR]','void',NULL,NULL,84,'SqlSetAttribute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,89,4,'java.sql.PreparedStatement','executeQuery',1114175038570,1114175038571,'[]','weblogic.jdbc.wrapper.ResultSet_weblogic_jdbcx_bas',NULL,NULL,84,'SqlExecute');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,90,5,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','endMethod',1114175038571,1114175038572,'[V_CURR.select_by_functionnal_key]','void',NULL,NULL,84,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,91,0,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','endMethod',1114175038571,1114175038572,'[V_CURR.select_by_functionnal_key1114175038569]','void',NULL,NULL,90,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,92,2,'org.javamonitoring.snapshot.application2.server.datamgr.currency.CurrencyDataMgr','populateBusiness',1114175038572,1114175038572,'[org.javamonitoring.snapshot.framework.server.datamgr.JdbcWrapper@ad9f8a]','[ISOCode=EUR | context=[mUserLogin = user_ok mUser',NULL,NULL,80,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,93,3,'org.javamonitoring.snapshot.common.server.datamgr.CommonDataMgr','closeJdbcWrapper',1114175038573,1114175038574,'[org.javamonitoring.snapshot.framework.server.datamgr.JdbcWrapper@ad9f8a]','void',NULL,NULL,80,'DataMgr');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,94,12,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','setValorisation',1114175038576,1114175038580,'[org.javamonitoring.snapshot.application.interop.soa.dto.gsastatofholdings.StatOfHoldingsResultSetResul t@13d832[ISOCode=EUR | context=[mUserLogin = user_ok mUserId = null mUserPassword = password mApp','true',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,95,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getStatOfHoldingsOrchestrationServiceHel',1114175038577,1114175038577,'[]','org.javamonitoring.snapshot.application.interop.orchestration.statemen',NULL,NULL,94,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,96,1,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustodiansMerged',1114175038577,1114175038577,'[]','[]',NULL,NULL,94,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,97,2,'org.javamonitoring.snapshot.framework.interop.orchestrationservice.OrchestrationService','getBasicService',1114175038577,1114175038580,'[[mUserLogin = user_ok mUserId = null mUserPassword = password mApplicationDate = null mEntityId = 0 mEntityLabel = null mUserId = null mLanguage = en mLanguageCountry = GB mConnectionToken = 0 mEntit','org.javamonitoring.snapshot.application2.server.basicservice.valorisati',NULL,NULL,94,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,98,13,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationService','getStatOfHoldingsOrchestrationServiceHel',1114175038580,1114175038580,'[]','org.javamonitoring.snapshot.application.interop.orchestration.statemen',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,99,14,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanTree',1114175038580,1114175038583,'[]','void',NULL,NULL,7,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,100,0,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListQuantityAdded',1114175038581,1114175038581,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,101,1,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038581,1114175038581,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,102,2,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListAvailabilityTypeAdded',1114175038581,1114175038581,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,103,3,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038581,1114175038581,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,104,4,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListBalanceQualifierAdded',1114175038581,1114175038581,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,105,5,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038581,1114175038581,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,106,6,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustodianSafeKeepingAccountAdded',1114175038581,1114175038581,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,107,7,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038582,1114175038582,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,108,8,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustodianAdded',1114175038582,1114175038582,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,109,9,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038582,1114175038582,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,110,10,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListSecurityLegalTypeAdded',1114175038582,1114175038582,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,111,11,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038582,1114175038582,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,112,12,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListSecurityAdded',1114175038582,1114175038582,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,113,13,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038582,1114175038582,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,114,14,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','getListCustomerSafeKeepingAccountAdded',1114175038583,1114175038583,'[]','[]',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,115,15,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038583,1114175038583,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,116,16,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038583,1114175038583,'[[]]','void',NULL,NULL,99,'Orchestration');
 INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,117,17,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038583,1114175038583,'[[]]','void',NULL,NULL,99,'Orchestration');
INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,118,18,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038584,1114175038585,'[[]]','void',NULL,NULL,99,'Orchestration');

INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,119,19,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038585,1114175038587,'[[]]','void',NULL,NULL,99,'Orchestration');

INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,120,20,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038587,1114175038589,'[[]]','void',NULL,NULL,99,'Orchestration');

INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,121,21,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038589,1114175038591,'[[]]','void',NULL,NULL,99,'Orchestration');

INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,122,22,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038591,1114175038594,'[[]]','void',NULL,NULL,99,'Orchestration');

INSERT INTO method_call (FLOW_ID, INDEX_IN_FLOW, SUB_METH_INDEX, FULL_CLASS_NAME, METHOD_NAME,BEGIN_TIME, END_TIME, PARAMETERS, RESULT, THROWABLE_CLASS_NAME,THROWABLE_MESSAGE, PARENT_INDEX_IN_FLOW , GROUP_NAME)VALUES  (25010,123,23,'org.javamonitoring.snapshot.application.interop.orchestration.statofholdings.StatOfHoldingsOrchestrationServiceHelper','cleanAbstractTreeDTO',1114175038594,1114175038609,'[[]]','void',NULL,NULL,99,'Orchestration');


  UNLOCK TABLES;

LOCK TABLES execution_flow WRITE;

UPDATE EXECUTION_FLOW SET FIRST_METHOD_CALL_INDEX_IN_FLOW=1;
 UNLOCK TABLES;


/*!40000 ALTER TABLE method_call ENABLE KEYS */;


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;

/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;





 